name: Continue Integration Workflow

on:
  push:
    branches:
      - main
jobs:
  check_source:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Update value new
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          ENV: dev
          REPOSITORY: ${{ github.repository }}
          MYVARIABLE: "kkkkkk"
        run: |
          gh variable set MYVARIABLE --env $ENV --repo $REPOSITORY --body $MYVARIABLE